stages:
  - build
  - tests

build:regular:
  stage: build
  image: alex7r/lamp:ccp
  script:
    - if grep -rn './' -e "\xEF\xBB\xBF"; then exit 1; fi
    - grep -E -o '<version>(.*?)</version>' ./pkg_quiz.xml | sed -E 's/<version>|<\/version>//g' | while read version; do find ./com_joomlaquiz/admin/sql/updates/ -maxdepth 2 -name "*.sql" -print |  sed -E 's/.*\/|\.sql//g' | while read sqin; do if [ "$sqin" \> "$version" ]; then exit 1; fi; done; done
# delete updater temporary
    - sed -E -i 's/<file.*?_joomplaceupdater.zip<\/file>//g' ./pkg_quiz.xml
    - mkdir packages
    - grep -E -o '<file.*>(.*?)</file>' ./pkg_quiz.xml |  sed -E 's/<file[^>]+>|.zip<\/file>//g' | while read in; do if [ "$in" != 'plg_installer_joomplaceupdater' ]; then cd ./"$in"; zip -r ./../packages/"$in".zip ./*; cd ./../; fi; done
    - pwd
  artifacts:
    paths:
    - packages/
    - pkg_quiz.xml
    name: "pkg_quiz_${CI_BUILD_REF_NAME}"
    when: on_success
    expire_in: 1 day

test:regular:
  stage: tests
  variables:
    JUSERID: $[ ( $RANDOM % 100 )  + 1 ]
    JUSERNAME: "admin"
    JUSEREMAIL: "admin@localhost.com"
    JUSERPASS: "qweasd"
    DB: "joomla_test"
    DBUSER: "jdbuser"
    DBPASS: "dbupass"
    DBPREFIX: "prfx_"
    JOOMLAVERSION: "3.6.5"
  image: alex7r/lamp:ccp
  script:
    - pwd
    - echo "${JUSERID}"
    - echo "${JUSERNAME}"
  artifacts:
    paths:
    - packages/
    name: "tests_log_${CI_BUILD_REF_NAME}"
    when: on_success
    expire_in: 1 hour
  dependencies:
  - build:regular

build:expert:
  stage: build
  image: alex7r/lamp:ccp
  script:
    - if grep -rn './' -e "\xEF\xBB\xBF"; then exit 1; fi
    - grep -E -o '<version>(.*?)</version>' ./pkg_expert_quiz.xml | sed -E 's/<version>|<\/version>//g' | while read version; do find ./com_joomlaquiz_expert/admin/sql/updates/ -maxdepth 2 -name "*.sql" -print |  sed -E 's/.*\/|\.sql//g' | while read sqin; do if [ "$sqin" \> "$version" ]; then exit 1; fi; done; done
# delete updater temporary
    - sed -E -i 's/<file.*?_joomplaceupdater.zip<\/file>//g' ./pkg_expert_quiz.xml
    - mkdir packages
    - grep -E -o '<file.*>(.*?)</file>' ./pkg_expert_quiz.xml |  sed -E 's/<file[^>]+>|.zip<\/file>//g' | while read in; do if [ "$in" != 'plg_installer_joomplaceupdater' ]; then cd ./"$in"; zip -r ./../packages/"$in".zip ./*; cd ./../; fi; done
    - pwd
  artifacts:
    paths:
    - packages/
    - pkg_expert_quiz.xml
    name: "pkg_expert_quiz_${CI_BUILD_REF_NAME}"
    when: on_success
    expire_in: 1 day