-- SELECT CONCAT('ALTER TABLE `',TABLE_NAME,'` CHANGE `',COLUMN_NAME,'` `',COLUMN_NAME,'` ',COLUMN_TYPE,' ',IF(CHARACTER_SET_NAME IS NOT NULL,'CHARACTER SET utf8 COLLATE utf8_unicode_ci ',''),IF(IS_NULLABLE = "YES",'NULL','NOT NULL'),' ',IF(EXTRA NOT LIKE "", EXTRA, CONCAT(' DEFAULT ',IF(COLUMN_DEFAULT IS NOT NULL,CONCAT('"',COLUMN_DEFAULT,'"'),IF(IS_NULLABLE = "YES",'NULL','""')))),';') AS `SQLS` 
-- FROM information_schema.COLUMNS 
-- WHERE TABLE_SCHEMA != 'information_schema' AND TABLE_NAME LIKE '%_quiz%'
-- LIMIT 10;

ALTER TABLE `#__quiz_cert_fields` CHANGE `c_id` `c_id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_cert_fields` CHANGE `cert_id` `cert_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_cert_fields` CHANGE `f_text` `f_text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_cert_fields` CHANGE `text_x` `text_x` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_cert_fields` CHANGE `text_y` `text_y` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_cert_fields` CHANGE `text_h` `text_h` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_cert_fields` CHANGE `shadow` `shadow` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_cert_fields` CHANGE `font` `font` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT "arial.ttf";
ALTER TABLE `#__quiz_certificates` CHANGE `id` `id` int(12) NOT NULL auto_increment;
ALTER TABLE `#__quiz_certificates` CHANGE `cert_name` `cert_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_certificates` CHANGE `cert_file` `cert_file` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_certificates` CHANGE `crtf_align` `crtf_align` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_certificates` CHANGE `crtf_shadow` `crtf_shadow` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_certificates` CHANGE `text_x` `text_x` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_certificates` CHANGE `text_y` `text_y` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_certificates` CHANGE `text_size` `text_size` tinyint(4) NOT NULL  DEFAULT "10";
ALTER TABLE `#__quiz_certificates` CHANGE `crtf_text` `crtf_text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_certificates` CHANGE `text_font` `text_font` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_configuration` CHANGE `config_var` `config_var` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_configuration` CHANGE `config_value` `config_value` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_constants` CHANGE `c_id` `c_id` int(11) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_constants` CHANGE `key_value` `key_value` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_constants` CHANGE `default_value` `default_value` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_dashboard_items` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_dashboard_items` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_dashboard_items` CHANGE `url` `url` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_dashboard_items` CHANGE `icon` `icon` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_dashboard_items` CHANGE `published` `published` tinyint(1) NOT NULL  DEFAULT 1;
ALTER TABLE `#__quiz_export` CHANGE `eid` `eid` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_export` CHANGE `e_filename` `e_filename` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_export` CHANGE `e_date` `e_date` date NOT NULL  DEFAULT "0000-00-00";
ALTER TABLE `#__quiz_export` CHANGE `e_quizes` `e_quizes` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_feed_option` CHANGE `quiz_id` `quiz_id` int(11) NOT NULL  DEFAULT 0;
ALTER TABLE `#__quiz_feed_option` CHANGE `from_percent` `from_percent` char(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_feed_option` CHANGE `to_percent` `to_percent` char(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_feed_option` CHANGE `fmessage` `fmessage` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_languages` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_languages` CHANGE `lang_file` `lang_file` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_languages` CHANGE `is_default` `is_default` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_lpath` CHANGE `title` `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_lpath` CHANGE `paid_check` `paid_check` tinyint(1) NOT NULL  DEFAULT "1";
ALTER TABLE `#__quiz_lpath` CHANGE `short_descr` `short_descr` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_lpath` CHANGE `descr` `descr` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_lpath` CHANGE `published` `published` tinyint(4) NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_lpath` CHANGE `asset_id` `asset_id` int(18) NOT NULL  DEFAULT 0;
ALTER TABLE `#__quiz_lpath` CHANGE `lp_access_message` `lp_access_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_lpath_quiz` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_lpath_quiz` CHANGE `lid` `lid` int(11) NOT NULL  DEFAULT 0;
ALTER TABLE `#__quiz_lpath_quiz` CHANGE `type` `type` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_lpath_quiz` CHANGE `qid` `qid` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_quiz` CHANGE `order` `order` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_stage` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_lpath_stage` CHANGE `uid` `uid` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_stage` CHANGE `oid` `oid` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_stage` CHANGE `rel_id` `rel_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_stage` CHANGE `lpid` `lpid` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_stage` CHANGE `type` `type` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_stage` CHANGE `qid` `qid` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_stage` CHANGE `stage` `stage` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_lpath_stage` CHANGE `attempts` `attempts` int(5) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_payments` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_payments` CHANGE `processor` `processor` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_payments` CHANGE `status` `status` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_payments` CHANGE `amount` `amount` decimal(12,5) NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_payments` CHANGE `cur_code` `cur_code` char(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_payments` CHANGE `date` `date` datetime NULL  DEFAULT "0000-00-00 00:00:00";
ALTER TABLE `#__quiz_payments` CHANGE `pid` `pid` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_payments` CHANGE `user_id` `user_id` int(11) NULL  DEFAULT "0";
ALTER TABLE `#__quiz_payments` CHANGE `checked_out` `checked_out` int(11) NULL  DEFAULT "0";
ALTER TABLE `#__quiz_payments` CHANGE `checked_out_time` `checked_out_time` datetime NULL  DEFAULT "0000-00-00 00:00:00";
ALTER TABLE `#__quiz_payments` CHANGE `confirmed_time` `confirmed_time` datetime NULL  DEFAULT "0000-00-00 00:00:00";
ALTER TABLE `#__quiz_pool` CHANGE `q_id` `q_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_pool` CHANGE `q_cat` `q_cat` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_pool` CHANGE `q_count` `q_count` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_product_info` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_product_info` CHANGE `name` `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_product_info` CHANGE `quiz_sku` `quiz_sku` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_products` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_products` CHANGE `pid` `pid` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_products` CHANGE `type` `type` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_products` CHANGE `rel_id` `rel_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_products` CHANGE `xdays` `xdays` int(5) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_products` CHANGE `period_start` `period_start` date NOT NULL  DEFAULT "0000-00-00";
ALTER TABLE `#__quiz_products` CHANGE `period_end` `period_end` date NOT NULL  DEFAULT "0000-00-00";
ALTER TABLE `#__quiz_products` CHANGE `attempts` `attempts` int(5) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_products_stat` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_products_stat` CHANGE `uid` `uid` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_products_stat` CHANGE `oid` `oid` int(11) NULL  DEFAULT "0";
ALTER TABLE `#__quiz_products_stat` CHANGE `qp_id` `qp_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_products_stat` CHANGE `xdays_start` `xdays_start` datetime NOT NULL  DEFAULT "0000-00-00 00:00:00";
ALTER TABLE `#__quiz_products_stat` CHANGE `period_start` `period_start` date NOT NULL  DEFAULT "0000-00-00";
ALTER TABLE `#__quiz_products_stat` CHANGE `period_end` `period_end` date NOT NULL  DEFAULT "0000-00-00";
ALTER TABLE `#__quiz_products_stat` CHANGE `attempts` `attempts` int(3) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_q_cat` CHANGE `qc_id` `qc_id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_q_cat` CHANGE `qc_category` `qc_category` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_q_cat` CHANGE `qc_instruction` `qc_instruction` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_q_cat` CHANGE `qc_tag` `qc_tag` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_q_chain` CHANGE `quiz_id` `quiz_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_q_chain` CHANGE `user_id` `user_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_q_chain` CHANGE `q_chain` `q_chain` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_q_chain` CHANGE `s_unique_id` `s_unique_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_blank` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_r_student_blank` CHANGE `c_sq_id` `c_sq_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_blank` CHANGE `c_answer` `c_answer` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_blank` CHANGE `is_correct` `is_correct` tinyint(2) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_choice` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_r_student_choice` CHANGE `c_sq_id` `c_sq_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_choice` CHANGE `c_choice_id` `c_choice_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_hotspot` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_r_student_hotspot` CHANGE `c_sq_id` `c_sq_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_hotspot` CHANGE `c_select_x` `c_select_x` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_hotspot` CHANGE `c_select_y` `c_select_y` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_matching` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_r_student_matching` CHANGE `c_sq_id` `c_sq_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_matching` CHANGE `c_sel_text` `c_sel_text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_matching` CHANGE `c_matching_id` `c_matching_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_question` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_r_student_question` CHANGE `c_stu_quiz_id` `c_stu_quiz_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_question` CHANGE `c_question_id` `c_question_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_question` CHANGE `c_score` `c_score` float NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_question` CHANGE `c_attempts` `c_attempts` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_question` CHANGE `is_correct` `is_correct` tinyint(1) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_question` CHANGE `remark` `remark` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_question` CHANGE `reviewed` `reviewed` tinyint(1) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_question` CHANGE `c_flag_question` `c_flag_question` tinyint(2) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_quiz_id` `c_quiz_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_student_id` `c_student_id` int(11) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_total_score` `c_total_score` float NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_total_time` `c_total_time` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_date_time` `c_date_time` datetime NOT NULL  DEFAULT "0000-00-00 00:00:00";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_passed` `c_passed` tinyint(1) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `unique_id` `unique_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `allow_review` `allow_review` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_order_id` `c_order_id` int(11) NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_rel_id` `c_rel_id` int(11) NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_lid` `c_lid` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `unique_pass_id` `unique_pass_id` varchar(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_finished` `c_finished` tinyint(4) NULL  DEFAULT "1";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `user_email` `user_email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_passing_score` `c_passing_score` decimal(12,2) NOT NULL  DEFAULT "0.00";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `c_max_score` `c_max_score` decimal(12,2) NOT NULL  DEFAULT "0.00";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `user_name` `user_name` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `user_surname` `user_surname` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_quiz` CHANGE `params` `params` varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "{}";
ALTER TABLE `#__quiz_r_student_share` CHANGE `id` `id` int(12) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_r_student_share` CHANGE `c_quiz_id` `c_quiz_id` int(12) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_share` CHANGE `c_stu_quiz_id` `c_stu_quiz_id` int(12) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_share` CHANGE `c_user_id` `c_user_id` int(12) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_share` CHANGE `c_share_id` `c_share_id` varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_r_student_survey` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_r_student_survey` CHANGE `c_sq_id` `c_sq_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_r_student_survey` CHANGE `c_answer` `c_answer` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_setup` CHANGE `c_par_name` `c_par_name` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_setup` CHANGE `c_par_value` `c_par_value` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_blank` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_blank` CHANGE `c_question_id` `c_question_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_blank` CHANGE `ordering` `ordering` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_blank` CHANGE `points` `points` float NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_blank` CHANGE `css_class` `css_class` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_blank` CHANGE `c_quiz_id` `c_quiz_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_blank` CHANGE `gtype` `gtype` tinyint(1) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_category` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_category` CHANGE `c_category` `c_category` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_category` CHANGE `c_instruction` `c_instruction` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_choice` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_choice` CHANGE `c_choice` `c_choice` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_choice` CHANGE `c_right` `c_right` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_choice` CHANGE `c_question_id` `c_question_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_choice` CHANGE `ordering` `ordering` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_choice` CHANGE `c_incorrect_feed` `c_incorrect_feed` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_choice` CHANGE `a_point` `a_point` float NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_choice` CHANGE `c_quiz_id` `c_quiz_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_ext_hotspot` CHANGE `c_id` `c_id` int(12) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_ext_hotspot` CHANGE `c_question_id` `c_question_id` int(12) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_ext_hotspot` CHANGE `c_paths` `c_paths` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_faketext` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_faketext` CHANGE `c_quest_id` `c_quest_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_faketext` CHANGE `c_text` `c_text` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_hotspot` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_hotspot` CHANGE `c_question_id` `c_question_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_hotspot` CHANGE `c_start_x` `c_start_x` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_hotspot` CHANGE `c_start_y` `c_start_y` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_hotspot` CHANGE `c_width` `c_width` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_hotspot` CHANGE `c_height` `c_height` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_matching` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_matching` CHANGE `c_question_id` `c_question_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_matching` CHANGE `c_left_text` `c_left_text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_matching` CHANGE `c_right_text` `c_right_text` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_matching` CHANGE `ordering` `ordering` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_matching` CHANGE `c_quiz_id` `c_quiz_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_matching` CHANGE `a_points` `a_points` float NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_pbreaks` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_pbreaks` CHANGE `c_quiz_id` `c_quiz_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_pbreaks` CHANGE `c_question_id` `c_question_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_qtypes` CHANGE `c_id` `c_id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_qtypes` CHANGE `c_qtype` `c_qtype` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_qtypes` CHANGE `c_type` `c_type` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_question` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_question` CHANGE `c_quiz_id` `c_quiz_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_point` `c_point` float NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_attempts` `c_attempts` int(11) unsigned NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_question` CHANGE `c_question` `c_question` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_question` CHANGE `c_image` `c_image` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_question` CHANGE `c_type` `c_type` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `ordering` `ordering` int(11) NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_right_message` `c_right_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_t_question` CHANGE `c_wrong_message` `c_wrong_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_t_question` CHANGE `c_feedback` `c_feedback` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `cq_id` `cq_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_ques_cat` `c_ques_cat` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_random` `c_random` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_partial` `c_partial` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_partially_message` `c_partially_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_question` CHANGE `published` `published` tinyint(4) NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_question` CHANGE `c_title_true` `c_title_true` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_t_question` CHANGE `c_title_false` `c_title_false` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_t_question` CHANGE `c_qform` `c_qform` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `report_name` `report_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_question` CHANGE `c_layout` `c_layout` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_separator` `c_separator` tinyint(4) NOT NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_question` CHANGE `c_manual` `c_manual` tinyint(1) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_penalty` `c_penalty` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_immediate` `c_immediate` tinyint(1) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_question` CHANGE `c_detailed_feedback` `c_detailed_feedback` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_category_id` `c_category_id` int(11) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_user_id` `c_user_id` int(11) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_author` `c_author` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_full_score` `c_full_score` float NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_title` `c_title` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_description` `c_description` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_short_description` `c_short_description` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL  DEFAULT NULL;
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_image` `c_image` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_time_limit` `c_time_limit` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_min_after` `c_min_after` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_passing_score` `c_passing_score` float NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_created_time` `c_created_time` date NOT NULL  DEFAULT "0000-00-00";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_published` `c_published` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_right_message` `c_right_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_wrong_message` `c_wrong_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_pass_message` `c_pass_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_unpass_message` `c_unpass_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_enable_review` `c_enable_review` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_email_to` `c_email_to` tinyint(1) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_email_chk` `c_email_chk` tinyint(1) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_enable_print` `c_enable_print` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_enable_sertif` `c_enable_sertif` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_skin` `c_skin` tinyint(3) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_random` `c_random` tinyint(1) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_guest` `c_guest` tinyint(1) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `published` `published` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_slide` `c_slide` tinyint(4) NOT NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_language` `c_language` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_certificate` `c_certificate` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_feedback` `c_feedback` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_pool` `c_pool` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_resbycat` `c_resbycat` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_feed_option` `c_feed_option` char(1) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_show_quest_pos` `c_show_quest_pos` tinyint(4) NOT NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_show_quest_points` `c_show_quest_points` tinyint(4) NOT NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_show_author` `c_show_author` tinyint(1) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_show_timer` `c_show_timer` tinyint(4) NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_once_per_day` `c_once_per_day` tinyint(4) NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_emails` `c_emails` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_timer_style` `c_timer_style` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_statistic` `c_statistic` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_metadescr` `c_metadescr` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_keywords` `c_keywords` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_metatitle` `c_metatitle` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_ismetadescr` `c_ismetadescr` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_iskeywords` `c_iskeywords` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_ismetatitle` `c_ismetatitle` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_number_times` `c_number_times` int(11) NOT NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_pagination` `c_pagination` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_enable_prevnext` `c_enable_prevnext` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `paid_check` `paid_check` tinyint(1) NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_quiz` CHANGE `paid_check_descr` `paid_check_descr` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_allow_continue` `c_allow_continue` tinyint(1) NOT NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_autostart` `c_autostart` tinyint(4) NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_redirect_after` `c_redirect_after` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_redirect_delay` `c_redirect_delay` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_redirect_linktype` `c_redirect_linktype` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_redirect_link` `c_redirect_link` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_grading` `c_grading` tinyint(1) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_ifmanual` `c_ifmanual` tinyint(1) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_enable_skip` `c_enable_skip` tinyint(3) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_show_result` `c_show_result` tinyint(3) NOT NULL  DEFAULT "1";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_show_qfeedback` `c_show_qfeedback` tinyint(3) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_flag` `c_flag` tinyint(3) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_hide_feedback` `c_hide_feedback` tinyint(3) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_auto_breaks` `c_auto_breaks` tinyint(5) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_share_buttons` `c_share_buttons` tinyint(3) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `asset_id` `asset_id` int(18) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_quiz_access_message` `c_quiz_access_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_quiz` CHANGE `c_quiz_certificate_access_message` `c_quiz_certificate_access_message` text CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_text` CHANGE `c_id` `c_id` int(10) unsigned NOT NULL auto_increment;
ALTER TABLE `#__quiz_t_text` CHANGE `c_blank_id` `c_blank_id` int(10) unsigned NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_text` CHANGE `c_text` `c_text` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";
ALTER TABLE `#__quiz_t_text` CHANGE `ordering` `ordering` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_text` CHANGE `c_quiz_id` `c_quiz_id` int(11) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_t_text` CHANGE `regexp` `regexp` tinyint(4) NOT NULL  DEFAULT "0";
ALTER TABLE `#__quiz_templates` CHANGE `id` `id` int(11) NOT NULL auto_increment;
ALTER TABLE `#__quiz_templates` CHANGE `template_name` `template_name` varchar(250) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL  DEFAULT "";